import type { Match } from "../types/index";

export const matches: Match[] = [
  {
    id: "1",
    category: "major",
    board: "Live",
    duration: "1h",
    league: "Crypto Majors",
    title: "BTC vs ETH",
    subtitle: "Who outperforms over the next hour?",
    left: { ticker: "BTC", odds: 1.76, change: "+0.84%" },
    draw: { odds: 3.4, change: "Tie move" },
    right: { ticker: "ETH", odds: 1.94, change: "+0.62%" },
    pool: 64800,
    entries: 412,
    timer: "43m left",
    status: "live",
  },
  {
    id: "2",
    category: "major",
    board: "Live",
    duration: "4h",
    league: "Crypto Majors",
    title: "SOL vs AVAX",
    subtitle: "Which coin wins this momentum round?",
    left: { ticker: "SOL", odds: 1.68, change: "+1.24%" },
    draw: { odds: 4.1, change: "Tie move" },
    right: { ticker: "AVAX", odds: 2.05, change: "+0.73%" },
    pool: 52300,
    entries: 295,
    timer: "3h 08m left",
    status: "live",
  },
  {
    id: "3",
    category: "altcoin",
    board: "Live",
    duration: "15m",
    league: "Altcoin Arena",
    title: "TIA vs INJ",
    subtitle: "Fast round. Pick the stronger mover.",
    left: { ticker: "TIA", odds: 1.88, change: "+0.33%" },
    draw: { odds: 3.8, change: "Tie move" },
    right: { ticker: "INJ", odds: 1.83, change: "+0.41%" },
    pool: 19900,
    entries: 188,
    timer: "09m left",
    status: "live",
  },
  {
    id: "4",
    category: "meme",
    board: "Live",
    duration: "30m",
    league: "Meme Arena",
    title: "DOGE vs PEPE",
    subtitle: "Meme battle live now.",
    left: { ticker: "DOGE", odds: 1.91, change: "+2.13%" },
    draw: { odds: 4.45, change: "Tie move" },
    right: { ticker: "PEPE", odds: 1.85, change: "+1.98%" },
    pool: 27100,
    entries: 210,
    timer: "18m left",
    status: "live",
  },
  {
    id: "5",
    category: "major",
    board: "Upcoming",
    duration: "1D",
    league: "Crypto Majors",
    title: "XRP vs BNB",
    subtitle: "Daily battle opens shortly.",
    left: { ticker: "XRP", odds: 2.08, change: "Starts soon" },
    draw: { odds: 5.0, change: "Tie move" },
    right: { ticker: "BNB", odds: 1.66, change: "Starts soon" },
    pool: 48120,
    entries: 337,
    timer: "Starts in 22m",
    status: "upcoming",
  },
  {
    id: "6",
    category: "altcoin",
    board: "Upcoming",
    duration: "1h",
    league: "Solana Board",
    title: "SOL vs JUP",
    subtitle: "Upcoming Solana ecosystem clash.",
    left: { ticker: "SOL", odds: 1.78, change: "Starts soon" },
    draw: { odds: 4.2, change: "Tie move" },
    right: { ticker: "JUP", odds: 1.96, change: "Starts soon" },
    pool: 21400,
    entries: 140,
    timer: "Starts in 11m",
    status: "upcoming",
  },
];