[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
preda_program = "ASduBgEErytSwohRDtmhYxZs38FHBqg4CVcDWpkFdSkz"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
